# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ay5dNNCO7IRjZnz1nYJ53PHdcWrQ4SbU
"""

import os
import torch
from torch import nn, optim
from torchvision import datasets, transforms, models
import argparse
from torch.utils.data import DataLoader
from collections import OrderedDict

# Parse command line arguments
def parse_args():
    parser = argparse.ArgumentParser(description='Train a neural network on a dataset')
    parser.add_argument('data_dir', type=str, help='Path to dataset')
    parser.add_argument('--save_dir', type=str, default='./', help="Directory to save the model checkpoint.")
    parser.add_argument('--architecture', type=str, default='vgg16', help="Model architecture")
    parser.add_argument('--epochs', type=int, default=10, help='Number of training epochs')
    parser.add_argument('--hidden_units', type=int, default=512, help="Number of hidden units in the classifier.")
    parser.add_argument('--learning_rate', type=float, default=0.001, help='Learning rate')
    parser.add_argument('--gpu', action='store_true', help="Use GPU for training.")

    return parser.parse_args()


# Load data
def load_data(data_directory):
    """Loads training and validation datasets with transformations applied."""

    train_path = os.path.join(data_directory, 'train')
    validation_path = os.path.join(data_directory, 'valid')

    train_transform = transforms.Compose([
        transforms.RandomRotation(30),
        transforms.RandomResizedCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    validation_transform = transforms.Compose([
        transforms.Resize(255),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    train_dataset = datasets.ImageFolder(train_path, transform=train_transform)
    validation_dataset = datasets.ImageFolder(validation_path, transform=validation_transform)

    train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=32, shuffle=True)
    validation_loader = torch.utils.data.DataLoader(validation_dataset, batch_size=32)

    return train_loader, validation_loader, train_dataset

# Build model
def build_model(arch, hidden_units):
    if arch == "vgg13":
        model = models.vgg13(pretrained=True)
        input_features = 25088
    elif arch == 'resnet18':
        model = models.resnet18(pretrained=True)
        input_features = 9216
        arch = "alexnet"
    else:
        raise ValueError(f"The architecture is unsupported. Please choose vgg16 model or resnet18 model.")

    # Freeze parameters so we don't backpropagate through them
    for param in model.parameters():
        param.requires_grad = False


    # Define classifier
    classifier = nn.Sequential(
        OrderedDict([
                ("fc1", nn.Linear(input_features, 4096)),
                ("relu1", nn.ReLU()),
                ("dropout1", nn.Dropout(p=0.3)),
                ("fc2", nn.Linear(4096, hidden_units)),
                ("relu2", nn.ReLU()),
                ("dropout2", nn.Dropout(p=0.3)),
                ("fc3", nn.Linear(hidden_units, 102)),
                ("output", nn.LogSoftmax(dim=1)),]))

    model.classifier = classifier
    return model, arch


# Train model
def train_model(model, train_loader, valid_loader, criterion, optimizer, device, epochs):
    model.to(device)
    train_loss,valid_loss, accuracy = 0, 0, 0

    for epoch in range(epochs):
        model.train()

        # Training
        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        # Validation
        model.eval()

        with torch.no_grad():
            for inputs, labels in valid_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                valid_loss += loss.item()

                # Accuracy
                top_class = outputs.argmax(dim=1)
                accuracy += (top_class == labels).float().mean().item()

        # Output training and validation results
        print(f"Epoch {epoch+1}/{epochs}.. "
              f"Train Loss: {train_loss/len(train_loader):.3f}.. "
              f"Validation Loss: {valid_loss/len(valid_loader):.3f}.. "
              f"Validation Accuracy: {accuracy/len(valid_loader):.2f}")


# Save trained model
def save_checkpoint(model, save_dir, arch, hidden_units, train_data):
    checkpoint = {
        'arch': arch,
        'hidden_units': hidden_units,
        'state_dict': model.state_dict(),
        'class_to_idx': train_data.class_to_idx,
        "hidden_units":hidden_units,
    }

    save_path = os.path.join(save_dir, 'checkpoint.pth')
    torch.save(checkpoint, save_path)
    print(f"Checkpoint saved ")


# Main function
def main():
    args = parse_args()
    train_loader = load_data(args.data_dir, args.batch_size)
    model = build_model()
    trained_model = train_model(model, train_loader, args.epochs, args.learning_rate)
    save_checkpoint(trained_model, args.save_path)

if __name__ == "__main__":
    main()